version: '2'
services:
  mysql:
    build: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/sql/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE: bible
      - MYSQL_ROOT_PASSWORD:
    networks:
      - network-1

networks:
  network-1:
    driver: bridge
